Add CI
willmcgugan/declare pull request #9
Opened 2024-04-14 18:23 UTC by davidbrochart

2024-04-14 19:34 UTC, bswck requested changes

2024-04-14 19:34 UTC, bswck commented on .github/workflows/test.yml
> +        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
I see this matrix slightly suboptimal.
https://blog.jaraco.com/efficient-use-of-ci-resources

2024-04-14 19:34 UTC, bswck commented on .github/workflows/test.yml
> +        uses: actions/setup-python@v4.7.1
I think it is worth setting to setup-python@v5.
[v5.1.0 is the latest release](https://github.com/actions/setup-python/releases).

2024-04-14 19:34 UTC, bswck commented on .github/workflows/test.yml
> +    strategy:
```suggestion
    strategy:
      fail-fast: false
```

2024-04-14 19:34 UTC, bswck commented on .github/workflows/test.yml
> +          cache: 'poetry'
```suggestion
          cache: poetry
```
For consistency.

2024-04-19 10:43 UTC, willmcgugan commented
Thanks @davidbrochart 

Merging for now. @bswck feel free to PR your changes. I don't know enough about GA to review.

2024-04-19 10:43 UTC, merged